name: turf_booking
description: A turf booking application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  supabase_flutter: ^2.8.3
  supabase_auth_ui: ^0.5.4
  flutter_web_auth_2: ^2.1.4
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  http: ^1.1.0
  intl: ^0.19.0
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  carousel_slider: ^5.0.0
  table_calendar: ^3.0.9
  shimmer: ^3.0.0
  fl_chart: ^0.65.0
  permission_handler: ^11.3.0
  google_generative_ai: ^0.2.0
  markdown: ^7.2.1
  flutter_gemini: ^2.0.1
  json_annotation: ^4.8.1
  web_socket_channel: ^2.4.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/visa_logo.png
    - .env
    - assets/images/turf.png
